import {TREES,summary,lockReason,changeNode,normalizeTree,nodeRows,treeStats,treeWarnings,isAutomaticNode,SHEET_MASTERY_NODES} from './mastery-tree.js?v=passive-sheet-1';
const MASTERY_ICON_OVERRIDES={Wand_High_Attack_01:'icons/mastery/curse-duration.png?v=centered-2',Wand_Rare_Attack_01:'icons/mastery/periodic-damage.png?v=centered-2'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v).toLocaleString('ru-RU',{maximumFractionDigits:2});
const colors={common:'#a3adba',uncommon:'#64ad84',rare:'#739fe6',epic:'#b68bea'};
export function mountMastery(panel,getState,catalog,onChange){
 let selected={CR:null,WA_GR:null};
 const label=k=>catalog.labels[k]||({int:'Мудрость',range_damage_dealt_modifier:'Урон дальнего боя',magic_damage_dealt_modifier:'Урон магии',move_speed_modifier:'Скорость передвижения',magic_doll_heal_modifier:'Исцеление амитоем',debuff_taken_duration_modifier:'Длительность негативных эффектов',buff_given_duration_modifier:'Длительность положительных эффектов'}[k])||k;
 const format=(k,v)=>num(v*(catalog.formats[k]?.mul??(k.endsWith('_modifier')?.01:1)))+(catalog.formats[k]?.suffix??(k.endsWith('_modifier')?'%':''));
 const rows=rs=>rs.map(r=>`<div class="stat-line"><span>${esc(label(r.stat))}</span><b>${r.value>0?'+':''}${esc(format(r.stat,r.value))}</b></div>`).join('');
 panel.innerHTML=`<div class="section-head"><h2>Мастерство оружия</h2><a href="https://rutl.org/builder" target="_blank" rel="noopener">Данные RUTL ↗</a></div><p class="hint">Нажми узел: +1. Правая кнопка мыши: −1. Выбранный узел можно изменить кнопками под деревом. Обычные узлы — до 10 уровней. Ключевые узлы открываются автоматически и не расходуют очки. По 200 очков на оружие.</p><div class="mastery-trees">${Object.entries(TREES).map(([key,t])=>`<section class="mastery-weapon"><div class="section-head"><h3>${key==='CR'?'Арбалет':'Жезл · книжка'}</h3><b id="mastery-count-${key}"></b></div><div class="mastery-scroll"><div class="mastery-map" id="mastery-map-${key}"></div></div><div class="mastery-node-detail" id="mastery-detail-${key}"></div></section>`).join('')}</div><p id="mastery-message" role="status" aria-live="polite"></p><p class="micro">Кольца открываются после 30 очков на предыдущем кольце. Ключевой узел автоматически включается при 20 очках своего сектора кольца. На кольце открывается не более двух ключевых узлов. Эпические узлы: 80/120 очков и открытый ключевой узел своего сектора. Снятие необходимых очков снимает зависимые узлы.</p><p class="notice">Постоянные числовые бонусы обоих деревьев прибавляются к сборке. Связки «Славное возмездие» / «Славное возрождение» и «Выгодный момент» / «Амбидекстр» учитываются в характеристиках. Остальные условные эффекты перечислены ниже.</p><div id="mastery-warnings"></div><h3>Итоговые прибавки мастерства</h3><div class="mastery-trees">${Object.entries(TREES).map(([k,t])=>`<div><h4>${esc(t.name)}</h4><div id="mastery-bonuses-${k}"></div></div>`).join('')}</div><details><summary>Итоговые боевые характеристики · сборка + мастерство</summary><div id="mastery-totals" class="sim-fields"></div></details>`;
 function update(key,id,delta){const focusNode=document.activeElement?.dataset?.node,state=getState(),tree=TREES[key],before=state.masteryTrees[key];selected[key]=id;const result=changeNode(tree,before,id,delta);state.masteryTrees[key]=result.selected;const removed=Object.keys(before).filter(k=>k!==id&&before[k]&&!result.selected[k]).length;draw();if(focusNode)panel.querySelector('[data-node="'+focusNode+'"]')?.focus({preventScroll:true});panel.querySelector('#mastery-message').textContent=result.error||(removed?`Снято зависимых узлов: ${removed}.`:'Очки мастерства сохранены.');if(!result.error)onChange();}
 function details(key){
  const tree=TREES[key],n=tree.nodes.find(n=>n.id===selected[key]),box=panel.querySelector('#mastery-detail-'+key);
  if(!n){box.innerHTML='<p class="hint">Выбери узел, чтобы увидеть бонусы и уровни.</p>';return;}
  const choice=getState().masteryTrees[key],l=choice[n.id]||0,reason=lockReason(tree,n,choice),rs=nodeRows(n,l||1),automatic=isAutomaticNode(n);
  const sectorNames={attack:'Атака',util:'Поддержка',defense:'Защита',tactic:'Тактика'},pointSummary=summary(tree,choice);
  const sectors=automatic?`<p class="micro">${Object.entries(sectorNames).map(([sector,name])=>`${name}: ${pointSummary.sectors[n.ring+':'+sector]||0} / ${n.required||20}`).join(' · ')}. Не более двух ключевых узлов на кольце.</p>`:'';
  const controls=automatic?`<p class="notice">${l?'Открыт автоматически':'Закрыт'} · 0 очков</p>`:`<div class="mastery-stepper"><button data-minus aria-label="Убрать очко" ${l?'':'disabled'}>−</button><b>${l} / ${n.max}</b><button data-plus aria-label="Добавить очко" ${reason||l>=n.max?'disabled':''}>+</button></div>`;
  box.innerHTML=`<h4>${esc(n.name)}</h4>${controls}${sectors}<p class="micro">${esc(reason||(automatic?'Условия выполнены':'Узел доступен'))}${!rs.length?(SHEET_MASTERY_NODES.has(n.id)?' · Бонус учитывается при выборе связанной пассивки':' · Эффект не включён в DPS'):''}</p><p class="description">${esc(n.text)}</p><p class="micro">${l?'Текущий бонус':'Бонус при открытии'}</p>${rows(rs)}`;
  if(!automatic){box.querySelector('[data-minus]').onclick=()=>update(key,n.id,-1);box.querySelector('[data-plus]').onclick=()=>update(key,n.id,1);}
 }
 function draw(){const state=getState();for(const [key,tree] of Object.entries(TREES)){
  const choice=state.masteryTrees[key]=normalizeTree(tree,state.masteryTrees[key]);panel.querySelector('#mastery-count-'+key).textContent=summary(tree,choice).total+' / 200';
  const map=panel.querySelector('#mastery-map-'+key);map.innerHTML=`<svg viewBox="0 0 1000 1000" aria-hidden="true">${[200,326,452].map((r,i)=>`<circle cx="500" cy="500" r="${r}" fill="none" stroke="${Object.values(colors)[i]}" opacity=".22"/>`).join('')}${tree.links.map(l=>`<polyline points="${l.points.map(p=>p.x+','+p.y).join(' ')}" fill="none" stroke="${choice[l.from]&&choice[l.to]?l.color:'#303b4d'}" stroke-width="${choice[l.from]&&choice[l.to]?5:2}"/>`).join('')}</svg><span class="mastery-center">${key==='CR'?'Арбалет':'Жезл'}<small>Мастерство</small></span>${tree.nodes.map(n=>{const l=choice[n.id]||0,locked=lockReason(tree,n,choice),automatic=isAutomaticNode(n);return `<button type="button" class="mastery-node ${l?'chosen':''} ${locked?'locked':''} ${selected[key]===n.id?'focused':''} ${n.type==='synergy'?'synergy':''}" style="left:${n.x/10}%;top:${n.y/10}%;--node-color:${colors[n.grade]}" data-node="${esc(n.id)}" title="${esc(n.name+' · '+(automatic?(l?'Открыт автоматически':'Закрыт'):l+'/'+n.max)+(locked?' · '+locked:''))}" aria-label="${esc(n.name+' '+(automatic?(l?'открыт автоматически':'закрыт'):l+' из '+n.max))}" aria-pressed="${Boolean(l)}"><img class="${MASTERY_ICON_OVERRIDES[n.id]?'original-mastery-icon':''}" src="${esc(MASTERY_ICON_OVERRIDES[n.id]||n.icon)}" alt="" loading="lazy"><span>${automatic?(l?'✓':'—'):l+'/'+n.max}</span></button>`;}).join('')}`;
  map.querySelectorAll('[data-node]').forEach(b=>{const n=tree.nodes.find(n=>n.id===b.dataset.node),automatic=isAutomaticNode(n);b.onclick=()=>{if(automatic){selected[key]=n.id;draw();}else update(key,n.id,1);};b.oncontextmenu=e=>{e.preventDefault();if(!automatic)update(key,b.dataset.node,-1);};b.onkeydown=e=>{if(automatic)return;if(e.key==='-'||e.key==='ArrowDown'){e.preventDefault();if(!automatic)update(key,b.dataset.node,-1);}if(e.key==='ArrowUp'){e.preventDefault();update(key,b.dataset.node,1);}};});
  details(key);const stats=treeStats(state,key);panel.querySelector('#mastery-bonuses-'+key).innerHTML=rows(Object.entries(stats).filter(([,v])=>v).map(([stat,value])=>({stat,value})))||'<p class="micro">Очки ещё не распределены.</p>';
 }
 const ws=treeWarnings(state);panel.querySelector('#mastery-warnings').innerHTML=ws.length?`<details><summary>Неучтённые эффекты: ${ws.length}</summary><ul>${ws.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></details>`:'';
 }
 draw();return {draw};
}
