import assert from 'node:assert/strict';
import fs from 'node:fs';
import {deriveStats,simulate} from '../dist/simulator.js';
import {emptyMastery,applyMastery} from '../dist/mastery.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../dist/catalog.json',import.meta.url)));
const cross=catalog.equipment.find(x=>x.category==='Crossbow');
const state={items:{weapon1:{id:cross.id,level:0,traits:[]}},attrMode:'total',attrs:{str:40,dex:76,Int:76,per:40,con:11},active:[],passive:[],defensive:[],specs:{}};
const base=deriveStats(state,catalog);
assert.deepEqual(deriveStats({...state,mastery:emptyMastery()},catalog),base);
const mastered={...state,mastery:{...emptyMastery(),crossMax:50,critR:100,speed:10,mana:500}};
const result=deriveStats(mastered,catalog);
assert.equal(result.crossMax,base.crossMax+50);assert.equal(result.critR,base.critR+100);assert.equal(result.mana,base.mana+500);
assert(Math.abs(result.interval-base.interval*(1+base.speed/100)/(1+(base.speed+10)/100))<1e-12);
assert.equal(result.wandMax,base.wandMax);
const original=simulate({catalog,state,params:base,priority:[]});
assert(simulate({catalog,state:mastered,params:result,priority:[]}).dps>original.dps);
assert.deepEqual(simulate({catalog,state:mastered,params:base,priority:[]}),original,'Manual totals must not add mastery twice');
assert.deepEqual(applyMastery(base,{crossMax:NaN,critR:-100}),base);
console.log('Mastery: additive stats, speed interval, increased DPS, no manual double-counting, zero defaults passed.');
