import assert from 'node:assert/strict';
import fs from 'node:fs';
import {deriveStats,simulate} from '../dist/simulator.js';
import {emptyMastery,applyMastery} from '../dist/mastery.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../dist/catalog.json',import.meta.url)));
const cross=catalog.equipment.find(x=>x.category==='Crossbow');
const state={items:{weapon1:{id:cross.id,level:0,traits:[]}},attrMode:'total',attrs:{str:40,dex:76,Int:76,per:40,con:11},active:[],passive:[],defensive:[],specs:{}};
const base=deriveStats(state,catalog);
assert.deepEqual(deriveStats({...state,mastery:emptyMastery()},catalog),base);
const mastered={...state,mastery:{...emptyMastery(),crossMax:50,critR:100,speed:10,mana:500}};
const result=deriveStats(mastered,catalog);
assert.deepEqual(result,base,'Removed manual mastery must not affect saved builds');
const treeState={...state,masteryTrees:{CR:{Crossbow_Normal_Attack_01:10}}};
const treeResult=deriveStats(treeState,catalog);
assert.equal(treeResult.speed,base.speed+2.1);
assert(treeResult.interval<base.interval);
const original=simulate({catalog,state,params:base,priority:[]});
assert.deepEqual(simulate({catalog,state:mastered,params:result,priority:[]}),original);
assert.deepEqual(applyMastery(base,{crossMax:NaN,critR:-100}),base);
console.log('Mastery: legacy manual values ignored, real tree speed interval passed.');
