import assert from 'node:assert/strict';
import fs from 'node:fs';
import {deriveStats,passiveSheetEffects,passiveLevel,characterStats,statBreakdown,PASS} from '../dist/simulator.js';
import {TREES,normalizeTree,summary} from '../dist/mastery-tree.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../dist/catalog.json',import.meta.url)));
const revival='WP_WA_GR_S_HealEfficiencyByMaxCost';
const common={Wand_Normal_Attack_01:10,Wand_Normal_Attack_02:10,Wand_Normal_AttackUtil_03:10};
const wand={...common,Wand_High_Attack_01:10,Wand_High_Attack_02:10};
const cross={Crossbow_Normal_Attack_01:10,Crossbow_Normal_Attack_02:10,Crossbow_Normal_AttackUtil_03:10,Crossbow_High_Attack_01:10};
const state={items:{weapon1:{id:'crossbow_aa_t1_normal_010',level:11,traits:[]},weapon2:{id:'wand_aa_t5_boss_002',level:12,traits:[]}},attrs:{str:30,dex:79,Int:60,per:41,con:10},attrMode:'total',masteryTrees:{CR:cross,WA_GR:wand},active:[],defensive:[],specs:{},passive:[PASS.ambi,revival],passiveLevels:{[PASS.ambi]:4,[revival]:4}};
const near=(actual,expected)=>assert(Math.abs(actual-expected)<1e-9,`${actual} != ${expected}`);
const effects=passiveSheetEffects(state,catalog,12316);
near(effects.revival,36.08588);near(effects.baseDamagePercent,9.02147);
assert.equal(effects.offMaxBonus,38);assert.equal(effects.offChanceBonus,0);
const inactive={...state,masteryTrees:{CR:cross,WA_GR:common}};
assert.equal(passiveSheetEffects(inactive,catalog,12316).baseDamagePercent,0);
assert.equal(passiveSheetEffects({...state,passive:[PASS.ambi]},catalog,12316).baseDamagePercent,0);
assert.equal(passiveSheetEffects({...state,passive:[]},catalog,12316).offMaxBonus,0);
assert.equal(passiveLevel({...state,passiveLevels:{}},revival),5);
assert.equal(passiveLevel({...state,passiveLevels:{[revival]:'bad'}},revival),5);
const old=deriveStats({...inactive,passive:[]},catalog),withLevel4=deriveStats(inactive,catalog);
assert.equal(withLevel4.offMax,old.offMax+38);assert.equal(withLevel4.offhand,old.offhand);
const updated=deriveStats(state,catalog),percent=passiveSheetEffects(state,catalog,updated.mana).baseDamagePercent;
for(const key of ['crossMin','crossMax','offMin','offMax','wandMin','wandMax'])assert.equal(updated[key],withLevel4[key]+Math.floor(withLevel4[key]*percent/100));
near(updated.healing,withLevel4.healing*.7);
const paired=normalizeTree(TREES.CR,{...cross,Crossbow_High_Attack_02:10});
assert(paired.Crossbow_High_Attack_Skill);
const advantage=passiveSheetEffects({...state,masteryTrees:{...state.masteryTrees,CR:paired}},catalog,12316);
assert.equal(advantage.offMaxBonus,68);assert.equal(advantage.offChanceBonus,-4);
// Stored free flags cannot unlock a sector with only 10 points.
assert(!normalizeTree(TREES.CR,{...cross,Crossbow_High_Attack_Skill:1}).Crossbow_High_Attack_Skill);
const three=normalizeTree(TREES.CR,{Crossbow_Normal_Attack_01:10,Crossbow_Normal_Attack_02:10,Crossbow_Normal_Tactic_10:10,Crossbow_Normal_Tactic_11:10,Crossbow_Normal_Defense_07:10,Crossbow_Normal_Defense_08:10});
assert.equal(TREES.CR.nodes.filter(n=>n.ring===0&&n.type==='synergy'&&three[n.id]).length,2);
assert.equal(summary(TREES.CR,three).total,60);
const level5=deriveStats({...inactive,passiveLevels:{}},catalog);assert.equal(level5.offMax,withLevel4.offMax+2);
const weaken={...inactive,passive:['WP_CR_S_WeakenAccuracy'],passiveLevels:{WP_CR_S_WeakenAccuracy:4}};
near((characterStats(weaken,catalog).weaken_accuracy-characterStats({...weaken,passive:[]},catalog).weaken_accuracy)*catalog.formats.weaken_accuracy.mul,198);
const breakdown=statBreakdown(state,catalog);
assert.deepEqual(breakdown.total,updated);
for(const [key,values] of Object.entries(breakdown.values))near(values.reduce((a,b)=>a+b,0),updated[key]);
console.log('Passive sheet: RU Epic 4 coefficients, mana-dependent mastery, inactive synergy, separate offhand, max two free nodes, healing and breakdown passed.');
