import assert from 'node:assert/strict';
import fs from 'node:fs';
import {runeEffects,runeChoices,runeStats} from '../dist/runes.js';
import {deriveStats,statBreakdown} from '../dist/simulator.js';
import {createStore} from '../dist/storage.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../dist/catalog.json',import.meta.url)));
const item=catalog.equipment.find(x=>x.category==='Crossbow'&&x.runeSlots===3);
const choices=runeChoices(item);
const runes=['Attack','Assist','Defense'].map(type=>{const r=choices.find(r=>r.type===type&&r.grade==='kAA');return {runeId:r.id,stat:r.statPool[0].stat,level:80};});
const entry={id:item.id,level:0,traits:[],runes};
const effect=runeEffects(item,entry,catalog);assert.equal(effect.stats.dex,4);assert.equal(effect.stats.attack_speed_modifier,350);
assert.equal(runeEffects(item,{...entry,runes:runes.slice(0,2)},catalog).synergy.length,0);
const low=structuredClone(entry);const weak=choices.find(r=>r.type==='Attack'&&r.grade==='kC');low.runes[0]={runeId:weak.id,stat:weak.statPool[0].stat,level:20};assert.equal(runeEffects(item,low,catalog).stats.dex,2);
const state={items:{weapon1:entry},attrs:{str:10,dex:10,Int:10,per:10,con:10},attrMode:'base',active:[],passive:[],defensive:[],specs:{},mastery:{},masteryTrees:{}};
const plain={...state,items:{weapon1:{...entry,runes:[]}}};
assert(deriveStats(state,catalog).speed>deriveStats(plain,catalog).speed);
const total={...state,attrMode:'total'};assert.equal(deriveStats(total,catalog).speed-deriveStats({...plain,attrMode:'total'},catalog).speed,3.5);
const b=statBreakdown(state,catalog);for(const [key,values] of Object.entries(b.values))assert(Math.abs(values.reduce((a,b)=>a+b,0)-b.total[key])<1e-8);
assert.deepEqual(runeStats({...state,items:{}},catalog),{});
assert.deepEqual(runeEffects({...item,runeSlots:0},entry,catalog).stats,{});
assert.equal(runeEffects(item,{...entry,runes:[{runeId:runes[0].runeId,stat:'invalid',level:80}]},catalog).selected[0],null);
const memory=new Map(),store=createStore({getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)});store.save('build',{state});assert.deepEqual(store.get('build').state.items.weapon1.runes,runes);
console.log('Runes: source synergy, weakest grade, raw units, derived stats, breakdown, eligibility and persistence passed.');
