import assert from 'node:assert/strict';
import fs from 'node:fs';
import {gearStats,setStats} from '../dist/engine.js';
import {deriveStats,statBreakdown} from '../dist/simulator.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../dist/catalog.json',import.meta.url)));
const pieces=catalog.equipment.filter(i=>i.setName==='Честь полководца');
const state={items:{head:{id:pieces[0].id,level:0,traits:[]}},attrs:{str:10,dex:10,Int:10,per:10,con:10},attrMode:'base',active:[],passive:[],defensive:[],specs:{},masteryTrees:{}};
assert.deepEqual(setStats(state,catalog),{});
const two={...state,items:{...state.items,chest:{id:pieces[1].id,level:0,traits:[]}}};
assert.equal(setStats(two,catalog).damage_reduction,18);
assert.equal(gearStats(two,catalog).damage_reduction-gearStats({...two,excludeSetBonuses:true},catalog).damage_reduction,18);
const three={...two,items:{...two.items,hands:{id:pieces[2].id,level:0,traits:[]}}};
assert.equal(setStats(three,catalog).damage_reduction,18,'A set bonus must not be repeated per piece');
assert.deepEqual(setStats({...state,items:{...state.items,chest:state.items.head}},catalog),{},'A duplicate item must not complete a set');
const c=structuredClone(catalog);for(const i of c.equipment.filter(i=>i.setName==='Честь полководца'))i.setBonuses=[{pieces:2,stats:[{type:'hp_max',value:1000},{type:'AllCriticalAttack',value:1000},{type:'SkillCooldownModifier',value:500}]}];
const without=deriveStats({...two,excludeSetBonuses:true},c),withSet=deriveStats(two,c);
assert.equal(withSet.hp-without.hp,1000);assert.equal(withSet.critR-without.critR,100);assert.equal(withSet.critM-without.critM,100);assert.equal(withSet.cooldown-without.cooldown,5);
const b=statBreakdown(two,c);assert.equal(b.values.hp[b.labels.indexOf('Комплекты')],1000);assert.deepEqual(b.total,withSet);
console.log('Equipment sets: real threshold, no duplicated bonuses, removed piece, source units and breakdown passed.');
