import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DEFAULTS,IDS,PASS,simulate,optimize,expectedHit,deriveStats} from '../dist/simulator.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../dist/catalog.json',import.meta.url)));
const state={items:{},attrs:{str:10,dex:10,Int:10,per:10,con:10},active:[],passive:[],defensive:[],specs:{}};
const params={...DEFAULTS,crossMin:100,crossMax:100,wandMin:100,wandMax:100,interval:1,mana:100000,regen:0};
assert.equal(expectedHit(params,'Crossbow',1,0),100);
assert.equal(expectedHit({...params,critR:1000,crossMax:200},'Crossbow',1,0),175);
assert.equal(expectedHit({...params,heavyR:1000,bonus:10},'Crossbow',1,0),160);
assert.equal(expectedHit({...params,defense:2500},'Crossbow',1,0),50);
let r=simulate({catalog,state,params,priority:[]},true);
assert.equal(r.total,30000);assert.equal(r.dps,100);assert.equal(r.bins.reduce((a,b)=>a+b,0),r.total);
let dot=simulate({catalog,state,params:{...params,auto:0},priority:[IDS.touch]},true);
assert(dot.total>0);assert(dot.logs.every(x=>x.time<300));assert(dot.mana>=0);
let base={catalog,state:{...state,active:[IDS.touch,IDS.area,IDS.burst,IDS.rapid,IDS.mark]},params:{...params,auto:1,critR:1000,heavyR:300},mode:'selected',budget:40};
let best=optimize(base);
assert(best.dps>=best.baseline);assert.deepEqual(optimize(base),best);assert(best.priority.length<=12);assert.equal(best.logs.length,Object.values(best.counts).reduce((a,b)=>a+b,0));
assert(Math.abs(Object.values(best.damage).reduce((a,b)=>a+b,0)-best.total)<1e-6);
let oom=simulate({catalog,state,params:{...params,mana:0,auto:0},priority:[IDS.rapid]},true);assert.equal(oom.total,0);assert.equal(oom.logs.length,0);assert(oom.starved>299);
let rapid=simulate({catalog,state,params:{...params,auto:0},priority:[IDS.rapid]},true);
let rapidSpec=simulate({catalog,state:{...state,specs:{[IDS.rapid]:['SkillSet_WP_CR_CR_S_RapidShot_Trait_2']}},params:{...params,auto:0},priority:[IDS.rapid]},true);assert(rapidSpec.total>rapid.total);
let unsupported=optimize({...base,state:{...state,active:[IDS.rapid],passive:[PASS.thirst]},mode:'all',budget:20});assert(unsupported.dps>=unsupported.baseline,'passive does not prohibit equipping the beam');
const initial=deriveStats(state,catalog),wisdom=deriveStats({...state,attrs:{...state.attrs,Int:60}},catalog);assert(wisdom.mana>initial.mana);assert(wisdom.cooldown>initial.cooldown);
console.log(JSON.stringify({checks:'passed',autoDps:r.dps,optimizedDps:best.dps,baseline:best.baseline,casts:best.logs.length}));
const once={...params,auto:0};
const touchOnce=simulate({catalog,state,params:once,priority:[IDS.touch],overrides:{[IDS.touch]:{cooldownSec:999,cast:0,hitDelay:0}}});
assert.equal(touchOnce.total,9*78,'one unrefreshed curse must have nine ticks');
const popped=simulate({catalog,state,params:once,priority:[IDS.touch,IDS.burst],burstStacks:1,overrides:{[IDS.touch]:{cooldownSec:999,cast:0,hitDelay:0},[IDS.burst]:{cooldownSec:999}}});
assert.equal(popped.damage[IDS.touch],78,'consumed curse must stop ticking');
assert(Math.abs(popped.damage['curse-explosion']-8*78*1.05)<1e-7,'remaining damage is not multiplied by crit/heavy twice');
const preserved=simulate({catalog,state:{...state,specs:{[IDS.burst]:['SkillSet_WP_WA_GR_S_CurseBurst_trait_1']}},params:once,priority:[IDS.touch,IDS.burst],burstStacks:1,overrides:{[IDS.touch]:{cooldownSec:999,cast:0,hitDelay:0},[IDS.burst]:{cooldownSec:999}}});
assert.equal(preserved.damage[IDS.touch],9*78);assert(Math.abs(preserved.damage['curse-explosion']-4*78*1.05)<1e-7);
for(let i=1;i<best.logs.length;i++)assert(best.logs[i].time+1e-6>=best.logs[i-1].time+best.logs[i-1].duration,'actions may not overlap');
console.log('Curse ticks, consumption, preservation and action timing: passed');
const natureState={...state,active:[IDS.nature],specs:{[IDS.nature]:['SkillSet_WP_CR_CR_S_AddProjectile_Trait_2']}};
const natureFull=simulate({catalog,state:natureState,params,priority:[IDS.nature]},true);
assert.equal(natureFull.logs[0].id,IDS.nature);assert.equal(natureFull.logs[0].duration,0);assert.equal(natureFull.counts[IDS.nature],1);
assert.equal(natureFull.damage['nature-hit'],300*21);assert.equal(natureFull.natureMana,300*23);assert(Math.abs(natureFull.natureUptime-300)<1e-7);
const natureLow=simulate({catalog,state:natureState,params:{...params,mana:100,regen:0},priority:[IDS.nature]},true);
assert.equal(natureLow.natureMana,92);assert.equal(natureLow.damage['nature-hit'],84);assert.equal(natureLow.mana,8);assert.equal(natureLow.natureStops,1);
assert.equal(expectedHit({...params,offMin:50,offMax:50},'Crossbow',1,0,{off:true}),50);
assert.deepEqual([...best.priority].sort(),[...base.state.active].sort(),'selected mode must preserve the supported panel');
const {totalAttributes}=await import('../dist/engine.js');
const sample=catalog.equipment.find(e=>e.extraStats?.dex>0);assert(sample);
const withGear={...state,attrs:{...state.attrs,dex:80},items:{head:{id:sample.id,level:0,traits:[]}}};
assert.equal(totalAttributes({...withGear,attrMode:'total'},catalog).dex,80);
assert(totalAttributes({...withGear,attrMode:'base'},catalog).dex>80);
assert.equal(deriveStats({...withGear,attrMode:'total'},catalog).speed,deriveStats({...withGear,attrMode:'base',attrs:{...withGear.attrs,dex:80-sample.extraStats.dex}},catalog).speed);
console.log('Toggle uptime, mana drain/cutoff, separate offhand, fixed panel and attribute modes: passed');
const {specCost}=await import('../dist/engine.js');
const {specializationOptions,allocateSpecializations}=await import('../dist/simulator.js');
const jointInput={catalog,state,params,mode:'all',budget:40};
const joint=optimize(jointInput);
assert.equal(specCost({...state,active:joint.priority,specs:joint.specs},catalog),joint.specPoints);assert(joint.specPoints<=100);
assert(joint.priority.length<=12);assert.equal(new Set(joint.priority).size,joint.priority.length);
for(const id of joint.priority)assert(specializationOptions(catalog,id).some(o=>JSON.stringify(o.ids)===JSON.stringify(joint.specs[id])),'legal specialization set');
assert.deepEqual(joint,optimize(jointInput),'joint search must be repeatable');
const replay=simulate({...jointInput,state:{...state,active:joint.priority,specs:joint.specs},priority:joint.priority,burstStacks:joint.burstStacks},true);
assert.equal(replay.total,joint.total,'returned specialization snapshot must reproduce reported damage');
assert(optimize({...jointInput,budget:60}).dps>=joint.dps,'more search preserves incumbent');
assert(allocateSpecializations(catalog,[IDS.nature]),'partial budgets are valid');
assert(specializationOptions(catalog,IDS.buck).every(o=>o.ids.length<=1),'replacement skills are exclusive');
assert(specializationOptions(catalog,IDS.nature).every(o=>o.ids.length===1),'one precombat element');
assert.deepEqual(best.specs,base.state.specs,'fixed panel preserves specializations');
console.log('Joint skill/spec search: budget at most 100, legal choices, deterministic replay and monotone search passed');
const {BUFF_DEFAULTS,lightBonusAt,specializationRole}=await import('../dist/simulator.js');
const spec=(id,n)=>catalog.skills.find(s=>s.id===id).specializations.find(t=>t.id.endsWith('_'+n)).id;
const buffRun=(id,ns,extra={})=>simulate({catalog,state:{...state,active:[id],specs:{[id]:ns.map(n=>spec(id,n))}},params:{...params,...BUFF_DEFAULTS,...extra},priority:[id],overrides:{[id]:{cooldownSec:999,cast:0,hitDelay:0}}},true);
const lightBase=buffRun(IDS.light,[]),lightSelf=buffRun(IDS.light,[1]),lightLong=buffRun(IDS.light,[1,3]),lightGroup=buffRun(IDS.light,[1,2]);
assert.equal(lightBase.total,30000,'base defensive light has no damage bonus');
assert(lightSelf.total>lightBase.total);assert(lightLong.total>lightSelf.total);
assert.equal(lightGroup.total,lightSelf.total,'group light does not multiply target count');
assert.equal(lightSelf.bins.at(-1),lightBase.bins.at(-1),'bonus expires');
assert.equal(lightSelf.effectEvents[0].target,'self');
assert(Math.abs(lightLong.effectEvents[0].end-lightSelf.effectEvents[0].end-1)<1e-8);
const opening={...BUFF_DEFAULTS,lightOpeningMultiplier:2};
assert.equal(lightBonusAt(0,1,7,false,opening),0,'no retroactive bonus');
assert.equal(lightBonusAt(1,1,7,false,opening),100);
assert.equal(lightBonusAt(3,1,7,false,opening),50);
assert.equal(lightBonusAt(7,1,7,false,opening),0);
assert.equal(lightBonusAt(1,1,7,true,opening),50,'directed version removes opening boost');
for(const weapon of ['Crossbow','Wand'])for(const off of [false,true])assert(expectedHit({...params,offMin:100,offMax:100},weapon,1,0,{off,maxBonus:50})>expectedHit({...params,offMin:100,offMax:100},weapon,1,0,{off}));
const selfDecay=buffRun(IDS.decay,[1]),baseDecay=buffRun(IDS.decay,[]),thirdDecay=buffRun(IDS.decay,[3]);
assert.equal(selfDecay.effectEvents[0].target,'self');assert.equal(baseDecay.effectEvents[0].target,'enemy');
assert.equal(baseDecay.total,thirdDecay.total,'trait 3 retains base effect on monster');
assert.equal(selfDecay.effectEvents[0].value,80);assert.equal(baseDecay.effectEvents[0].value,-220);
assert.equal(expectedHit({...params,resistance:700},'Wand',1,0),50);
assert(expectedHit({...params,resistance:700},'Wand',1,0,{resistanceDrop:220})>50);
const selfState={...state,active:[IDS.decay,IDS.rapid],passive:[PASS.thirst],specs:{[IDS.decay]:[spec(IDS.decay,1)]}};
const selfBattle=simulate({catalog,state:selfState,params:{...params,...BUFF_DEFAULTS},priority:selfState.active,overrides:{[IDS.decay]:{cooldownSec:999}}},true);
assert(Math.abs(selfBattle.effectEvents[0].end-selfBattle.effectEvents[0].time-9)<1e-8,'attacks do not extend personal buff');
const damageOnly=simulate({catalog,state:selfState,params:{...params,...BUFF_DEFAULTS,selfSkillBoost:0},priority:selfState.active},true);
const withSelf=simulate({catalog,state:selfState,params:{...params,...BUFF_DEFAULTS},priority:selfState.active},true);
assert(withSelf.total>damageOnly.total,'self skill boost contributes to subsequent skill hits');
const onlyMana=allocateSpecializations(catalog,[IDS.mana],{[IDS.mana]:[spec(IDS.mana,2)]},()=>.5,5);
assert.deepEqual(onlyMana[IDS.mana],[spec(IDS.mana,1)],'resource effect beats equally priced utility even when utility preferred');
assert.equal(specializationRole(IDS.mana,3),'utility');
console.log('Personal buffs, enemy debuff, expiry, directed light, resistance and useful-point preference passed');
